-- TASK 1 - How many employees is working for EACH department

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- TASK 2 - What is Max_salary / min_salary / total_expense / avg for each department

SELECT DEPARTMENT_ID, MAX(SALARY), MIN(SALARY), SUM(SALARY), ROUND(AVG(SALARY)) AS "AVERAGE"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- TASK 3 - Ignore null departments
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID;

-- TASK 4 - Display department id where employees count is less than 5 and order the result descending

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)<5
ORDER BY COUNT(*) DESC ;

SELECT * FROM CUSTOMER;
SELECT * FROM ADDRESS;

--inner join
SELECT FIRST_NAME, LAST_NAME, ADDRESS, PHONE
FROM CUSTOMER JOIN ADDRESS
                    ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--left join
SELECT FIRST_NAME, LAST_NAME, ADDRESS, PHONE
FROM CUSTOMER LEFT JOIN ADDRESS
                   ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--right join
SELECT FIRST_NAME, LAST_NAME, ADDRESS, PHONE
FROM CUSTOMER RIGHT JOIN ADDRESS
                        ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

SELECT FIRST_NAME, LAST_NAME, ADDRESS, PHONE
FROM ADDRESS FULL JOIN CUSTOMER
                    ON CUSTOMER.ADDRESS_ID=ADDRESS.ADDRESS_ID;



--How many employees are working in each region ?
SELECT R.REGION_NAME, COUNT(*)
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
         JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
         JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
         JOIN REGIONS R ON C.REGION_ID = R.REGION_ID
GROUP BY R.REGION_NAME
ORDER BY 1;



